Howdy,

Get started
------------------------------
Emails sent to {{ mlist.email }} go to everyone in the group.


Add new members
------------------------------
Send an email to {{ mlist.email }} and CC any email addresses you want to add.
They will be sent an invitation.


Your group's web site
------------------------------
Before you can use the site for your group you'll need
to create an account. If you're just using email, skip this,
you can always do it later.

1. Go to {{ mlist.url }}

2. Click on the link "create an account"


If you have any questions please let us know at support@email.postosaurus.com.
Or follow us on twitter @postosaurus.

Sincerely,
Postosaurus Rex

P.S.
Rooooooooar!!
