Howdy,

Welcome to {{ mlist.name }}.


What is Postosaurus?

Postosaurus is a lightweight project management application built around email. 
If you know how to use email, you know how to use Postosaurus. 


What can I do with Postosaurus?

Send emails to your group
--------------------------

To send an email to your group simply send an email to {{ mlist.email }}. This
message will be sent to everyone on your team.


Add new members to your group
-----------------------------

To add new members to your group, send an email to {{mlist.email}} 
and CC any email addresses you want to add. That's it!


Manage your group
------------------

Postosaurus provides a website for each group. Here are a few things you
can do through the site:

-- Review any links or urls ever sent to the group. If you have ever sent
a url to the group, you can see it here: {{ mlist.links_url() }}

-- Remove members from your group here: {{ mlist.members_url() }}

-- All emails sent to the group are saved so you can find them easily later.
View your group's archive here: {{ mlist.archive_url() }}


Create your account
-------------------

Before you can use the site for your group you'll need
to create an account. To do that visit any of the urls above.


If you have any questions or have any problems getting started just let us
know by sending an email to support@email.postosaurus.com.

Sincerely,
Postosaurus Rex

P.S.
Rooooooooar!!
