                                                                                                                                                                                                                                                               
Delivered-To: sean.fioritto@gmail.com
Received: by 10.216.5.19 with SMTP id 19cs94326wek;
        Sun, 8 Nov 2009 14:46:44 -0800 (PST)
Received: by 10.224.65.40 with SMTP id g40mr3688109qai.333.1257720403140;
        Sun, 08 Nov 2009 14:46:43 -0800 (PST)
Return-Path: <fiorittos@postosaurus.com>
Received: from postosaurus.com (ec2-174-129-39-206.compute-1.amazonaws.com [174.129.39.206])
        by mx.google.com with ESMTP id 30si2698931qyk.8.2009.11.08.14.46.42;
        Sun, 08 Nov 2009 14:46:43 -0800 (PST)
Received-SPF: neutral (google.com: 174.129.39.206 is neither permitted nor denied by best guess record for domain of fiorittos@postosaurus.com) client-ip=174.129.39.206;
Authentication-Results: mx.google.com; spf=neutral (google.com: 174.129.39.206 is neither permitted nor denied by best guess record for domain of fiorittos@postosaurus.com) smtp.mail=fiorittos@postosaurus.com
Received: from domU-12-31-38-00-30-C6.compute-1.internal (localhost.localdomain [127.0.0.1])
	by postosaurus.com (Postfix) with ESMTP id A91DA282D1
	for <sean.fioritto@gmail.com>; Sun,  8 Nov 2009 22:46:42 +0000 (UTC)
X-Mailbox-Line: From nobody Sun Nov  8 16:46:42 2009
Content-Type: multipart/alternative; boundary="===============1771826235=="
MIME-Version: 1.0
Date: Sun, 8 Nov 2009 16:46:21 -0600
From: Lisa Fioritto <lfioritto@gmail.com>
List-Archive: <http://postosaurus.com/archives/fiorittos/>
List-Help: <http://postosaurus.com/help.html>
List-Id: fiorittos@postosaurus.com
List-Post: <mailto:fiorittos@postosaurus.com>
List-Subscribe: <mailto:fiorittos-subscribe@postosaurus.com>
List-Unsubscribe: <mailto:fiorittos-unsubscribe@postosaurus.com>
Message-Id: <79d7ac290911081446r7d5ef577y7b6fca8cb8ab8035@mail.gmail.com>
Precedence: list
References: <5f1d9b0c0911081342s3f78cc14ideafefd2ec7e2fbd@mail.gmail.com> 
	<5f1d9b0c0911081342s3f78cc14ideafefd2ec7e2fbd@mail.gmail.com>
Reply-To: fiorittos@postosaurus.com
Sender: fiorittos@postosaurus.com
Subject: Re: Postosaurus testing
To: fiorittos@files.postosaurus.com

--===============1771826235==
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: 7bit

This painting gives Mike warm fuzzies because it reminds him of himself at
this age.

http://www.artic.edu/aic/collections/artwork/34145

On Sun, Nov 8, 2009 at 3:42 PM, Sean Fioritto <sean.fioritto@gmail.com>wrote:

> Hey family --
>
> Postosaurus now remembers links. You can see any links emailed to this
> group here:
> http://postosaurus.com/app/lists/12/links/
>
> You should see the link in a really ugly list. Josh will make that pretty
> later, but for now I'm hoping you can all help me test.
>
> How you say?
>
> Just send an email to our group (or reply to this email) and include some
> awesome links that we should all check out. Then go visit
> the link above. After a few seconds, (10 at most), the link you sent should
> appear on the list.
>
> Make sense? Questions? Thanks for the help!
>
> - Sean
>

--===============1771826235==
MIME-Version: 1.0
Content-Type: text/html; charset="us-ascii"
Content-Transfer-Encoding: 7bit

This painting gives Mike warm fuzzies because it reminds him of himself at this age.<br><br><a href="http://www.artic.edu/aic/collections/artwork/34145">http://www.artic.edu/aic/collections/artwork/34145</a><br><br><div class="gmail_quote">

On Sun, Nov 8, 2009 at 3:42 PM, Sean Fioritto <span dir="ltr">&lt;<a href="mailto:sean.fioritto@gmail.com">sean.fioritto@gmail.com</a>&gt;</span> wrote:<br><blockquote class="gmail_quote" style="border-left: 1px solid rgb(204, 204, 204); margin: 0pt 0pt 0pt 0.8ex; padding-left: 1ex;">

Hey family --<br><br>Postosaurus now remembers links. You can see any links emailed to this group here:<br><a href="http://postosaurus.com/app/lists/12/links/" target="_blank">http://postosaurus.com/app/lists/12/links/</a><br>

<br>You should see the link in a really ugly list. Josh will make that pretty later, but for now I&#39;m hoping you can all help me test.<br>
<br>How you say?<br><br>Just send an email to our group (or reply to this email) and include some awesome links that we should all check out. Then go visit<br>the link above. After a few seconds, (10 at most), the link you sent should appear on the list.<br>


<br>Make sense? Questions? Thanks for the help!<br><font color="#888888"><br>- Sean<br>
</font></blockquote></div><br>

--===============1771826235==--
