                                                                                                                                                                                                                                                               
Delivered-To: sean@allicator.com
Received: by 10.216.44.144 with SMTP id n16cs271715web;
        Mon, 9 Nov 2009 13:50:02 -0800 (PST)
Received: by 10.224.108.76 with SMTP id e12mr4390140qap.323.1257803401615;
        Mon, 09 Nov 2009 13:50:01 -0800 (PST)
Return-Path: <postosaurus@postosaurus.com>
Received: from postosaurus.com (ec2-174-129-39-206.compute-1.amazonaws.com [174.129.39.206])
        by mx.google.com with ESMTP id 2si109186qyk.111.2009.11.09.13.50.01;
        Mon, 09 Nov 2009 13:50:01 -0800 (PST)
Received-SPF: neutral (google.com: 174.129.39.206 is neither permitted nor denied by best guess record for domain of postosaurus@postosaurus.com) client-ip=174.129.39.206;
Authentication-Results: mx.google.com; spf=neutral (google.com: 174.129.39.206 is neither permitted nor denied by best guess record for domain of postosaurus@postosaurus.com) smtp.mail=postosaurus@postosaurus.com
Received: from domU-12-31-38-00-30-C6.compute-1.internal (localhost.localdomain [127.0.0.1])
	by postosaurus.com (Postfix) with ESMTP id D2AA8282C5
	for <sean@allicator.com>; Mon,  9 Nov 2009 21:50:00 +0000 (UTC)
X-Mailbox-Line: From nobody Mon Nov  9 15:50:00 2009
Content-Type: multipart/alternative; boundary="===============0623515845=="
MIME-Version: 1.0
Date: Mon, 9 Nov 2009 15:49:59 -0600
From: Sean Fioritto <sean.fioritto@gmail.com>
In-Reply-To: <5f1d9b0c0911091349i274a06ao8db2fd2f503b4357@mail.gmail.com>
List-Archive: <http://postosaurus.com/archives/postosaurus/>
List-Help: <http://postosaurus.com/help.html>
List-Id: postosaurus@postosaurus.com
List-Post: <mailto:postosaurus@postosaurus.com>
List-Subscribe: <mailto:postosaurus-subscribe@postosaurus.com>
List-Unsubscribe: <mailto:postosaurus-unsubscribe@postosaurus.com>
Message-Id: <5f1d9b0c0911091349i274a06ao8db2fd2f503b4357@mail.gmail.com>
Precedence: list
References: <5f1d9b0c0911091349i274a06ao8db2fd2f503b4357@mail.gmail.com>
Reply-To: postosaurus@postosaurus.com
Sender: postosaurus@postosaurus.com
Subject: oh, here's a nasty long url
To: postosaurus@postosaurus.com

--===============0623515845==
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: 7bit

http://www.google.com/reader/view/#stream/feed%2Fhttp%3A%2F%2Fsethgodin.typepad.com%2Fseths_blog%2Findex.rdf

And part of it is in the hash. Let's see if it picks it up.

--===============0623515845==
MIME-Version: 1.0
Content-Type: text/html; charset="us-ascii"
Content-Transfer-Encoding: 7bit

<a href="http://www.google.com/reader/view/#stream/feed%2Fhttp%3A%2F%2Fsethgodin.typepad.com%2Fseths_blog%2Findex.rdf">http://www.google.com/reader/view/#stream/feed%2Fhttp%3A%2F%2Fsethgodin.typepad.com%2Fseths_blog%2Findex.rdf</a><br>
<br>And part of it is in the hash. Let&#39;s see if it picks it up.<br>

--===============0623515845==--
