                                                                                                                                                                                                                                                               
MIME-Version: 1.0
Received: by 10.216.5.19 with HTTP; Sun, 8 Nov 2009 18:01:36 -0800 (PST)
In-Reply-To: <bca0ebe30911081758v7dece457m9e012b1ec83d88b7@mail.gmail.com>
References: <bca0ebe30911081758v7dece457m9e012b1ec83d88b7@mail.gmail.com>
	 <bca0ebe30911081758v7dece457m9e012b1ec83d88b7@mail.gmail.com>
Date: Sun, 8 Nov 2009 20:01:36 -0600
Delivered-To: sean.fioritto@gmail.com
Message-ID: <5f1d9b0c0911081801y6a853603vdf0f9b3ba27b3b1@mail.gmail.com>
Subject: Re: articles on self control
From: Sean Fioritto <sean.fioritto@gmail.com>
To: postosaurus@postosaurus.com
Content-Type: multipart/alternative; boundary=0016e6ddab5dcfb4a80477e6925a

--0016e6ddab5dcfb4a80477e6925a
Content-Type: text/plain; charset=ISO-8859-1

Strange. It had no problem picking these up but chopped my moms. The good
part about having them send me tests is I can download them and use them as
unit tests. :-)

P.S. This all works via the largest regular expression ever to know the
light of day. It's in app/model/links.py if you ever want to look. It's
straight copy-pasted from teh internets at the moment, but obviously I've
found a few bugs. Wish it would have worked perfectly...

- Sean

On Sun, Nov 8, 2009 at 7:58 PM, Sean Fioritto <sean@allicator.com> wrote:

> Some very interesting articles. Mainly a chance to test the url thingy. I
> think it will chop off the end of these links.
>
> Part 1:
> http://www.rolfnelson.com/2009/11/your-work-habits-and-happiness.html
>
> and Part 2
>
> http://www.rolfnelson.com/2009/11/how-to-follow-through-emerging-science.html
>

--0016e6ddab5dcfb4a80477e6925a
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

Strange. It had no problem picking these up but chopped my moms. The good p=
art about having them send me tests is I can download them and use them as =
unit tests. :-)<br><br>P.S. This all works via the largest regular expressi=
on ever to know the light of day. It&#39;s in app/model/links.py if you eve=
r want to look. It&#39;s straight copy-pasted from teh internets at the mom=
ent, but obviously I&#39;ve found a few bugs. Wish it would have worked per=
fectly...<br>
<br>- Sean<br><br><div class=3D"gmail_quote">On Sun, Nov 8, 2009 at 7:58 PM=
, Sean Fioritto <span dir=3D"ltr">&lt;<a href=3D"mailto:sean@allicator.com"=
>sean@allicator.com</a>&gt;</span> wrote:<br><blockquote class=3D"gmail_quo=
te" style=3D"border-left: 1px solid rgb(204, 204, 204); margin: 0pt 0pt 0pt=
 0.8ex; padding-left: 1ex;">
Some very interesting articles. Mainly a chance to test the url thingy. I t=
hink it will chop off the end of these links.<br><br>Part 1:<br><a href=3D"=
http://www.rolfnelson.com/2009/11/your-work-habits-and-happiness.html" targ=
et=3D"_blank">http://www.rolfnelson.com/2009/11/your-work-habits-and-happin=
ess.html</a><br>

<br>and Part 2<br><a href=3D"http://www.rolfnelson.com/2009/11/how-to-follo=
w-through-emerging-science.html" target=3D"_blank">http://www.rolfnelson.co=
m/2009/11/how-to-follow-through-emerging-science.html</a><br>
</blockquote></div><br>

--0016e6ddab5dcfb4a80477e6925a--